### ISSUE TITLE
Not an issue, just to ask smth

### ISSUE THREAD

**Issue by mxarment** [nedex/QuickNTP#12]
Is there anyway to make the QuickNTP to **update the hour-date periodically or every time I turn on** atmosphere???

I just figured out that my hour-date sometimes changes for no reason

**Comment by creeve4** [comment]
This would be a great feature!

**Comment by nedex** [comment]
As a Tesla plugin, this is technically not possible.

Instead, a "deamon" running in the background an periodically update the time would be more appropriate, but out of my scope.
