### ISSUE TITLE
Ability to Change time in the Menu

### ISSUE THREAD

**Issue by DraconicNEO** [nedex/QuickNTP#4]
I think it would be a good idea to be able to manually select a time in the app, the reason being that while you can do this in System settings it is limited there in such a way that you cannot set later dates than 2060, however it is shown that this isn't actually the Maximum date the Switch can actually use.

The idea is to allow users to manually set the time in the app in a way that isn't limited in the same way that the default method of system settings is.

**Comment by nedex** [comment]
What could be an use case of going after 2060?

**Comment by DraconicNEO** [comment]
> What could be an use case of going after 2060?

Time Travel in games beyond the normal display dates and future proofing.

**Comment by nedex** [comment]
> Time Travel in games beyond the normal display dates and future proofing.

Okay I get it.
By the way, developing another plugin to do so would be a better idea.

**Comment by DraconicNEO** [comment]
> > Time Travel in games beyond the normal display dates and future proofing.
> 
> Okay I get it. By the way, developing another plugin to do so would be a better idea.

Yeah actually that would make more sense.
