### ISSUE TITLE
OS Crash Firmware 15.1

### ISSUE THREAD

**Issue by adac7786** [nedex/QuickNTP#6]
Hello, ive updated to the most recent atmos and firmware today and opening the ntp overlay crashes the console. im encountering this on both of my consoles and just wanted to inform about the issue.

**Comment by nedex** [comment]
Hi, thanks for the report.

I'll update my hos too and check it out.

**Comment by nedex** [comment]
I've just updated to 15.0.1, Atmosphere 1.4.0 and it works correctly.

Does your console crash when you select QuickNTP or by pressing the button combo?
Could you try to install the latest nx-ovloader (1.0.6) and tesla menu (1.2.0)?

**Comment by adac7786** [comment]
my console crashes as soon as i hit the a button on quickntp in the overlay. im on 15.0.1 1.4.0 and on the same versions of ovloader and tesla as you, so i dont really understand whats going on here. im not sure if the error log is any good to you so ill just leave that here as well. this occurs on my v1 switch and oled which is using a v4 hwfly chip.

![Screenshot_4](https://user-images.githubusercontent.com/44790830/202860918-43f73f2e-47ec-4bba-b80b-5d7491e8c145.png)

**Comment by nedex** [comment]
Do you have any other sysmodules enabled?
Apparenyly having too much enabled may lead to your error code.

**Comment by adac7786** [comment]
this actually fixed my issue thanks. i didnt add any new modules and only upgraded my firmwares which was the reason why i assumed the os/atmos was the issue.
