### ISSUE TITLE
Crash on 16.0.0

### ISSUE THREAD

**Issue by rashevskyv** [nedex/QuickNTP#7]
Crash on launching with latest tesla .ovl https://github.com/WerWolv/Tesla-Menu/issues/50

**Comment by rashevskyv** [comment]
Thank you for your answer. You can use Atmosphere's libnx fork and 16.0.0 branch - https://github.com/Atmosphere-NX/libnx/tree/1600_support

**Comment by nedex** [comment]
Apparently it should be working also without the latest libnx version: https://github.com/WerWolv/nx-ovlloader/issues/22#issuecomment-1442536569

@rashevskyv could you try the latest pre-release?

https://github.com/nedex/QuickNTP/releases

**Comment by rashevskyv** [comment]
[nedex](https://github.com/nedex), works flawlessly, thank you
